### ISSUE TITLE
Setup Failed (release 1.0.0)

### ISSUE THREAD

**Issue by bsimmo** [pimoroni/weatherhat-python#33]
I followed the instructions
(had to install git)

It fails at the end with module errors etc.

It may or may not be related to NUMPY (see other separate report) but it is not saying it is that module, a quick look and I see _gpiodevice_ missing.

**Full** setup log here
Just a copy/paste of the first 3 steps from the setup box in the instructions at the start.

```
weatherhat@weatherhat:~ $ git clone https://github.com/pimoroni/weatherhat-python
cd weatherhat-python
./install.sh
Cloning into 'weatherhat-python'...
remote: Enumerating objects: 698, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 698 (delta 91), reused 100 (delta 86), pack-reused 548
Receiving objects: 100% (698/698), 143.73 KiB | 822.00 KiB/s, done.
Resolving deltas: 100% (400/400), done.
Installing weatherhat...

This script should be run in a virtual Python environment.
Would you like us to create and/or use a default one? [y/N] y

Creating a new virtual Python environment in /home/weatherhat/.virtualenvs/pimoroni, please wait...

Checking for /home/weatherhat/Pimoroni/auto_venv.sh

Creating /home/weatherhat/Pimoroni/auto_venv.sh


Checking Dependencies. Please wait...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: toml in /usr/lib/python3/dist-packages (0.10.2)

Installing for Python 3.11.2...


Installing stable library from pypi.

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting weatherhat
  Downloading https://www.piwheels.org/simple/weatherhat/weatherhat-1.0.0-py3-none-any.whl (13 kB)
Collecting ltr559>=1.0.0
  Downloading https://www.piwheels.org/simple/ltr559/ltr559-1.0.0-py3-none-any.whl (10 kB)
Collecting pimoroni-bme280>=1.0.0
  Downloading https://www.piwheels.org/simple/pimoroni-bme280/pimoroni_bme280-1.0.0-py3-none-any.whl (7.8 kB)
Collecting pimoroni-ioexpander>=1.0.1
  Downloading https://www.piwheels.org/simple/pimoroni-ioexpander/pimoroni_ioexpander-1.0.1-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 474.7 kB/s eta 0:00:00
Requirement already satisfied: smbus2 in /usr/lib/python3/dist-packages (from weatherhat) (0.4.2)
Collecting st7789>=1.0.1
  Downloading https://www.piwheels.org/simple/st7789/st7789-1.0.1-py3-none-any.whl (10 kB)
Collecting i2cdevice>=1.0.0
  Downloading https://www.piwheels.org/simple/i2cdevice/i2cdevice-1.0.0-py3-none-any.whl (10 kB)
Collecting gpiod
  Downloading https://www.piwheels.org/simple/gpiod/gpiod-2.2.0-cp311-cp311-linux_armv7l.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 535.0 kB/s eta 0:00:00
Collecting gpiodevice>=0.0.4
  Downloading https://www.piwheels.org/simple/gpiodevice/gpiodevice-0.0.5-py3-none-any.whl (9.2 kB)
Collecting numpy>=1.26.4
  Downloading numpy-2.0.0.tar.gz (18.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 624.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      + /home/weatherhat/.virtualenvs/pimoroni/bin/python /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0/vendored-meson/meson/meson.py setup /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0 /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0/.mesonpy-4vj13hqn -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0/.mesonpy-4vj13hqn/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0
      Build dir: /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0/.mesonpy-4vj13hqn
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 3.0.10)
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Program python found: YES (/home/weatherhat/.virtualenvs/pimoroni/bin/python)
      Found pkg-config: /usr/bin/pkg-config (1.8.1)
      Run-time dependency python found: YES 3.11
      Has header "Python.h" with dependency python: NO
      
      ../meson.build:44:2: ERROR: Problem encountered: Cannot compile `Python.h`. Perhaps you need to install python-dev|python-devel
      
      A full log can be found at /tmp/pip-install-q8v1fe8k/numpy_52287cc7c8a749409ab6f446cb4036f0/.mesonpy-4vj13hqn/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
⚠ WARNING: ^^^ 😬 previous command did not exit cleanly!
Done!

Using config.txt in /boot/firmware

Running setup commands...

Setting up i2c and SPI..
Backing up /boot/firmware/config.txt to /boot/firmware/config.preinstall-weatherhat-2024-06-23-14-37-25.txt

Running: "sudo raspi-config nonint do_spi 0"
Running: "sudo raspi-config nonint do_i2c 0"


Would you like to copy examples to /home/weatherhat/Pimoroni/weatherhat? [y/N] y
Copying examples to /home/weatherhat/Pimoroni/weatherhat
Done!

Would you like to install example dependencies? [y/N] y
Installing dependencies from requirements-examples.txt...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting fonts
  Downloading https://www.piwheels.org/simple/fonts/fonts-0.0.3-py3-none-any.whl (4.2 kB)
Collecting font-manrope
  Downloading https://www.piwheels.org/simple/font-manrope/font_manrope-0.0.2-py3-none-any.whl (366 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.6/366.6 kB 602.6 kB/s eta 0:00:00
Collecting pyyaml
  Downloading https://www.piwheels.org/simple/pyyaml/PyYAML-6.0.1-cp311-cp311-linux_armv7l.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 585.4 kB/s eta 0:00:00
Collecting adafruit-io
  Downloading https://www.piwheels.org/simple/adafruit-io/adafruit_io-2.7.2-py3-none-any.whl (22 kB)
Collecting numpy
  Using cached numpy-2.0.0.tar.gz (18.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      + /home/weatherhat/.virtualenvs/pimoroni/bin/python /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e/vendored-meson/meson/meson.py setup /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e/.mesonpy-487gv4t1 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e/.mesonpy-487gv4t1/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e
      Build dir: /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e/.mesonpy-487gv4t1
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 3.0.10)
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Program python found: YES (/home/weatherhat/.virtualenvs/pimoroni/bin/python)
      Found pkg-config: /usr/bin/pkg-config (1.8.1)
      Run-time dependency python found: YES 3.11
      Has header "Python.h" with dependency python: NO
      
      ../meson.build:44:2: ERROR: Problem encountered: Cannot compile `Python.h`. Perhaps you need to install python-dev|python-devel
      
      A full log can be found at /tmp/pip-install-5hg1d__a/numpy_e78cb89d51894ade9e9e7577acd5bf6e/.mesonpy-487gv4t1/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
⚠ WARNING: ^^^ 😬 previous command did not exit cleanly!

Would you like to generate documentation? [y/N] y
Installing pdoc. Please wait...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pdoc
  Downloading https://www.piwheels.org/simple/pdoc/pdoc-14.5.0-py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.4/134.4 kB 890.0 kB/s eta 0:00:00
Collecting Jinja2>=2.11.0
  Downloading https://www.piwheels.org/simple/jinja2/jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 574.4 kB/s eta 0:00:00
Collecting pygments>=2.12.0
  Downloading https://www.piwheels.org/simple/pygments/pygments-2.18.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.3 MB/s eta 0:00:00
Collecting MarkupSafe
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.5-cp311-cp311-linux_armv7l.whl (26 kB)
Installing collected packages: pygments, MarkupSafe, Jinja2, pdoc
Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 pdoc-14.5.0 pygments-2.18.0
Generating documentation.

Warn: Error loading weatherhat:
Traceback (most recent call last):
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py", line 218, in load_module
    return importlib.import_module(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/weatherhat/weatherhat-python/weatherhat/__init__.py", line 7, in <module>
    import gpiodevice
ModuleNotFoundError: No module named 'gpiodevice'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py", line 301, in walk_packages2
    module = load_module(mod.name)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py", line 220, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing weatherhat
 (/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py:303)
Traceback (most recent call last):
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py", line 218, in load_module
    return importlib.import_module(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/weatherhat/weatherhat-python/weatherhat/__init__.py", line 7, in <module>
    import gpiodevice
ModuleNotFoundError: No module named 'gpiodevice'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/__main__.py", line 286, in <module>
    cli()
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/__main__.py", line 199, in cli
    pdoc.pdoc(
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/__init__.py", line 520, in pdoc
    all_modules[module_name] = doc.Module.from_name(module_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/doc.py", line 404, in from_name
    return cls(extract.load_module(name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages/pdoc/extract.py", line 220, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing weatherhat
⚠ WARNING: Error: Failed to generate documentation.

⚠ WARNING: One or more setup commands appear to have failed.
This might prevent things from working properly.
Make sure your OS is up to date and try re-running this installer.
If things still don't work, report this or find help at https://www.github.com/pimoroni/weatherhat-python.

If this is your first time installing you should reboot for hardware changes to take effect.
Find uninstall steps in /home/weatherhat/Pimoroni/weatherhat/uninstall.sh

weatherhat@weatherhat:~/weatherhat-python $ 
```

**Comment by bsimmo** [comment]
So shut down.
Attached the WeatherHAT (how did I not notice that missing).

Went through the install again just to check (two numpy errors)
(This time it didn't try to run it itself)

So 
```
weatherhat@weatherhat:~/weatherhat-python $ source ~/.virtualenvs/pimoroni/bin/activate
(pimoroni) weatherhat@weatherhat:~/weatherhat-python $ ls
CHANGELOG.md  examples    LICENSE   pyproject.toml  requirements-dev.txt       testing  tox.ini       weatherhat
check.sh      install.sh  Makefile  README.md       requirements-examples.txt  tests    uninstall.sh
(pimoroni) weatherhat@weatherhat:~/weatherhat-python $ cd examples/
(pimoroni) weatherhat@weatherhat:~/weatherhat-python/examples $ ls
adafruit-io.py  averaging.py  basic.py  BME280-compensated.py  BME280.py  buttons.py  icons  lcd.py  settings.yml  weather.py
(pimoroni) weatherhat@weatherhat:~/weatherhat-python/examples $ python weather.py 
Traceback (most recent call last):
  File "/home/weatherhat/weatherhat-python/examples/weather.py", line 9, in <module>
    import gpiodevice
ModuleNotFoundError: No module named 'gpiodevice'
(pimoroni) weatherhat@weatherhat:~/weatherhat-python/examples $ 
```

As you can see the module is missing.

**Comment by bsimmo** [comment]
Seems it was NUMPY causing the problem
https://github.com/pimoroni/weatherhat-python/issues/32
Seems to have installed fine as shown below

```
weatherhat@weatherhat:~ $ cd ./weatherhat-python/
weatherhat@weatherhat:~/weatherhat-python $ ./install.sh
Installing weatherhat...

This script should be run in a virtual Python environment.
Would you like us to create and/or use a default one? [y/N] y

Activating existing virtual Python environment in /home/weatherhat/.virtualenvs/pimoroni

source "/home/weatherhat/.virtualenvs/pimoroni/bin/activate"

Checking Dependencies. Please wait...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: toml in /usr/lib/python3/dist-packages (0.10.2)

Installing for Python 3.11.2...


Installing stable library from pypi.

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting weatherhat
  Using cached https://www.piwheels.org/simple/weatherhat/weatherhat-1.0.0-py3-none-any.whl (13 kB)
Collecting ltr559>=1.0.0
  Using cached https://www.piwheels.org/simple/ltr559/ltr559-1.0.0-py3-none-any.whl (10 kB)
Collecting pimoroni-bme280>=1.0.0
  Using cached https://www.piwheels.org/simple/pimoroni-bme280/pimoroni_bme280-1.0.0-py3-none-any.whl (7.8 kB)
Collecting pimoroni-ioexpander>=1.0.1
  Using cached https://www.piwheels.org/simple/pimoroni-ioexpander/pimoroni_ioexpander-1.0.1-py3-none-any.whl (52 kB)
Requirement already satisfied: smbus2 in /usr/lib/python3/dist-packages (from weatherhat) (0.4.2)
Collecting st7789>=1.0.1
  Using cached https://www.piwheels.org/simple/st7789/st7789-1.0.1-py3-none-any.whl (10 kB)
Collecting i2cdevice>=1.0.0
  Using cached https://www.piwheels.org/simple/i2cdevice/i2cdevice-1.0.0-py3-none-any.whl (10 kB)
Collecting gpiod
  Using cached https://www.piwheels.org/simple/gpiod/gpiod-2.2.0-cp311-cp311-linux_armv7l.whl (90 kB)
Collecting gpiodevice>=0.0.4
  Using cached https://www.piwheels.org/simple/gpiodevice/gpiodevice-0.0.5-py3-none-any.whl (9.2 kB)
Collecting numpy>=1.26.4
  Downloading https://www.piwheels.org/simple/numpy/numpy-2.0.0-cp311-cp311-linux_armv7l.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 3.7 MB/s eta 0:00:00
Collecting spidev>=3.6
  Downloading https://www.piwheels.org/simple/spidev/spidev-3.6-cp311-cp311-linux_armv7l.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 1.7 MB/s eta 0:00:00
Installing collected packages: spidev, pimoroni-ioexpander, numpy, i2cdevice, gpiod, pimoroni-bme280, ltr559, gpiodevice, st7789, weatherhat
  Attempting uninstall: spidev
    Found existing installation: spidev 3.5
    Not uninstalling spidev at /usr/lib/python3/dist-packages, outside environment /home/weatherhat/.virtualenvs/pimoroni
    Can't uninstall 'spidev'. No files were found to uninstall.
Successfully installed gpiod-2.2.0 gpiodevice-0.0.5 i2cdevice-1.0.0 ltr559-1.0.0 numpy-2.0.0 pimoroni-bme280-1.0.0 pimoroni-ioexpander-1.0.1 spidev-3.6 st7789-1.0.1 weatherhat-1.0.0
Done!

Using config.txt in /boot/firmware

Running setup commands...

Setting up i2c and SPI..
Backing up /boot/firmware/config.txt to /boot/firmware/config.preinstall-weatherhat-2024-06-24-18-22-17.txt

Running: "sudo raspi-config nonint do_spi 0"
Running: "sudo raspi-config nonint do_i2c 0"


Would you like to copy examples to /home/weatherhat/Pimoroni/weatherhat? [y/N] y
Copying examples to /home/weatherhat/Pimoroni/weatherhat
Done!

Would you like to install example dependencies? [y/N] y
Installing dependencies from requirements-examples.txt...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting fonts
  Using cached https://www.piwheels.org/simple/fonts/fonts-0.0.3-py3-none-any.whl (4.2 kB)
Collecting font-manrope
  Using cached https://www.piwheels.org/simple/font-manrope/font_manrope-0.0.2-py3-none-any.whl (366 kB)
Collecting pyyaml
  Using cached https://www.piwheels.org/simple/pyyaml/PyYAML-6.0.1-cp311-cp311-linux_armv7l.whl (45 kB)
Collecting adafruit-io
  Using cached https://www.piwheels.org/simple/adafruit-io/adafruit_io-2.7.2-py3-none-any.whl (22 kB)
Requirement already satisfied: numpy in /home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages (from -r requirements-examples.txt (line 5)) (2.0.0)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/pillow/
Collecting pillow
  Downloading https://www.piwheels.org/simple/pillow/pillow-10.3.0-cp311-cp311-linux_armv7l.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.3 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from adafruit-io->-r requirements-examples.txt (line 4)) (2.28.1)
Collecting paho-mqtt
  Downloading https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-2.1.0-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.2/67.2 kB 1.4 MB/s eta 0:00:00
Installing collected packages: fonts, font-manrope, pyyaml, pillow, paho-mqtt, adafruit-io
Successfully installed adafruit-io-2.7.2 font-manrope-0.0.2 fonts-0.0.3 paho-mqtt-2.1.0 pillow-10.3.0 pyyaml-6.0.1

Would you like to generate documentation? [y/N] y
Installing pdoc. Please wait...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pdoc in /home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages (14.5.0)
Requirement already satisfied: Jinja2>=2.11.0 in /home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages (from pdoc) (3.1.4)
Requirement already satisfied: pygments>=2.12.0 in /home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages (from pdoc) (2.18.0)
Requirement already satisfied: MarkupSafe in /home/weatherhat/.virtualenvs/pimoroni/lib/python3.11/site-packages (from pdoc) (2.1.5)
Generating documentation.

Documentation saved to /home/weatherhat/Pimoroni/weatherhat/docs
Done!


All done!
If this is your first time installing you should reboot for hardware changes to take effect.
Find uninstall steps in /home/weatherhat/Pimoroni/weatherhat/uninstall.sh
```
